name: CI/CD Dummy Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

  push-image:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and publish a Docker image for alimuldev/tari-anjani-todo-web
        uses: macbre/push-to-ghcr@master
        with:
          image_name: alimuldev/tari-anjani-todo-web
          image_tag: v1.1
          github_token: ${{ secrets.GITHUB_TOKEN }}
          docker_io_token: ${{ secrets.DOCKER_IO_TOKEN }}
          docker_io_user: ${{ secrets.DOCKER_IO_USER }}

  deploy:
    runs-on: ubuntu-latest
    needs: push-image
    steps:
      - name: Deploy to VPS using SSH Passwords
        run: |
          sshpass -p "${{ secrets.VPS_SSH_PASSWORD }}" ssh -p 22 -o StrictHostKeyChecking=no "${{ secrets.VPS_USERNAME }}"@"${{ secrets.VPS_IP }}" << 'EOF'
            cd /home/apps/docker-runner/tari-anjani-todo-web-runner   # Sesuaikan dengan path aplikasi
            docker system prune -af || true
            docker compose pull tari-anjani-todo-web
            docker compose down -v tari-anjani-todo-web
            docker compose up -d tari-anjani-todo-web

            docker image prune -af
          EOF
        env:
          VPS_SSH_PASSWORD: ${{ secrets.VPS_SSH_PASSWORD }}
